Gemfile.lock
app/helpers/application_helper.rb
app/views/hong_baos/new/steps/_print.html.erb
app/views/hong_baos/pdf/_footer.html.erb

improve display pdf

---

e2e/playwright/e2e/pdf.spec.ts
e2e/playwright/support/on-rails.js
spec/fixtures/active_storage/attachments.yml
spec/fixtures/ai/face_swaps.yml
spec/fixtures/papers.yml

e2e spec for pdf

---

.github/workflows/README.md
.github/workflows/version-bump.yml

ft: github actions to bump version

---

app/admin/papers.rb

this only fixed the 500 error but i'll be working on active admin design and active admin is lagging

removed style from paper admin

---

app/javascript/controllers/canva_controller.js
app/javascript/controllers/canva_item_controller.js
app/javascript/controllers/hong_bao_controller.js
app/javascript/services/bitcoin/wallet.js
app/models/paper.rb
app/views/hong_baos/new/steps/_print.html.erb
app/views/hong_baos/new/steps/design/_canva_item.html.erb
config/routes.rb
db/migrate/20250505042804_update_app_public_address_qrcode_elements_to_papers.rb
db/schema.rb

180 pdf public address qrcode should go to /addrs/:addr

---

Gemfile.lock
app/jobs/process_paper_job.rb

set dimensions and quality + refactor path

---

app/models/bundle.rb
app/services/bundles/create.rb
e2e/playwright/e2e/bundle.spec.js

fix tokens

---

app/javascript/controllers/bitcoin_mnemonic_controller.js
app/javascript/services/bitcoin/master.js
app/views/hong_baos/show/_balance.html.erb
app/views/hong_baos/show/_private_key.html.erb
e2e/playwright/e2e/balance.spec.js
spec/fixtures/transaction_fees.yml

163 mnemonic to transfer is broken

---

app/admin/papers.rb
app/controllers/pages_controller.rb
app/models/paper.rb
db/migrate/20250516080641_remove_position_from_papers.rb
db/schema.rb
spec/fixtures/papers.yml

remove position and filter by active

---

app/components/qrcode_component.erb
app/components/qrcode_component.rb
app/helpers/application_helper.rb
app/helpers/qr_code_helper.rb
app/views/hong_baos/pdf/_footer.html.erb
app/views/papers/show.html.erb
config/routes.rb

305 pdf fix qrcodes

---

app/components/papers/item_component.erb

fix: add rounded-lg to Front face & Back face in ItemComponent's view

---

app/javascript/controllers/preview_controller.js

Add connect() in preview stimulus controller to check if a file is loaded, and reload it in the view's image src.

fix: check if a file is loaded, and reload it back to preview.src

---

app/components/analytics_component.html.erb
app/components/analytics_component.rb
app/views/hong_baos/show.html.erb
app/views/layouts/application.html.erb
app/views/papers/show.html.erb
app/views/shared/_clarity.html.erb
app/views/shared/_facebook_pixel.html.erb
spec/components/analytics_component_spec.rb

355 analytics install session replay clarity or so

---

app/controllers/application_controller.rb
app/controllers/papers_controller.rb
app/views/hong_baos/new/_header.html.erb
app/views/hong_baos/show/_balance.html.erb
app/views/layouts/application.html.erb
config/routes.rb

move default url to papers

---

app/components/papers/item_component.rb
app/components/progress_bar_component.html.erb
app/components/progress_bar_component.rb

374 enhance we should add a message wait 1 min user seemed confused as why the paper isnt showing

---

.github/workflows/deploy.yml

Reverts sbounmy/hongbao_bitcoin#436
which breaks arm64 https://github.com/lewagon/wait-on-check-action/issues/125

Revert "chore(deps): bump lewagon/wait-on-check-action from 1.3.4 to 1.4.0"

---

app/admin/javascript/controllers/visual_editor_controller.js
app/components/admin/visual_editor_component.rb
app/javascript/controllers/offline/bitcoin_controller.js
app/models/input/theme.rb
app/models/paper.rb
app/views/hong_baos/pdf/_footer.html.erb

- the App Qr Code (for maximalist mode) was not mirroring the beginner's qr code, and its size was 0, which made it look like it didn't exist.
- Visual Editor ignored the existence of app qr code.
- Add app qr code to the visual editor's hidden inputs
- Make the app qr code mirror the beginner's qr code
- Changed Input::Theme's default coordinates along the way.

383 scrollbug scroll in print page doesnt workbeneficiary toggle bug

---

Gemfile
Gemfile.lock
app/controllers/inputs_controller.rb
app/controllers/papers_controller.rb
app/models/input.rb
config/routes.rb
config/sitemap.rb
e2e/playwright/e2e/stripe.spec.js

529 seo bitcoininput

---

app/javascript/controllers/offline/pdf_controller.js
app/views/papers/_preview_pdf.html.erb
e2e/playwright/e2e/stripe.spec.js

- Zoom now follows the cursor
- Remove code smells and Refactor & dry code 
- Extract magic numbers into stimulus values
- Decrease zooming speed

[PDF VIEWER] Zoom on Cursor

---

app/admin/orders.rb
e2e/playwright/e2e/stripe.spec.js

Fix error when trying to view or edit an order in active admin

fix: error when editing/viewing an order fixed

---

app/admin/papers.rb
app/admin/tags.rb
app/models/concerns/taggable.rb
app/models/input.rb
app/models/paper.rb
app/models/tag.rb
app/views/papers/index.html.erb
db/migrate/20250821131413_add_tag_ids_to_papers.rb
db/schema.rb
e2e/playwright/e2e/paper_tags.spec.js
package.json
spec/fixtures/papers.yml
spec/fixtures/tags.yml
spec/models/concerns/array_columns_spec.rb
yarn.lock

581 paper add featured tab for featured papers
